version: '3.8'

services:
  web:
    build: .
    container_name: energy_prediction_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_DB=energy_prediction
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - app_network
    command: >
      bash -c "cd django_app &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14
    container_name: energy_prediction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=energy_prediction
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: